<?php
/** 
 * Copyright (c) 2011, Cédric DERUE
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the University of California, Berkeley nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

  //
  $this->broker('layout')->getLayout()->assign('header', 'Nouveau');
  $options = array();
  $options[] = array(
    'action' => 'Annuler',
    'icon'   => 'back',
    'url'    => '/contact/list'
  );
  $options[] = array(
    'action' => 'Sauver',
    'icon'   => 'check',
    'url'    => '/contact/create'
  );
  $this->broker('layout')->getLayout()->assign('footer', $options);
?>
<form method="post" action="/contact/create">
	<div data-role="fieldcontain">
    <label for="firstname">Prénom :</label>
    <input type="text" name="firstname" id="firstname" value="" />
	</div>
	<div data-role="fieldcontain">
    <label for="lastname">Nom :</label>
    <input type="text" name="lastname" id="lastname" value="" required />
	</div>
	<div data-role="fieldcontain">
    <label for="society">Société :</label>
    <input type="text" name="society" id="society" value="" required />
	</div>
	<div data-role="fieldcontain">
    <label for="job_title">Fonction :</label>
    <input type="text" name="job_title" id="job_title" value="" required />
	</div>
	<div data-role="fieldcontain">
    <label for="department">Département :</label>
    <input type="text" name="department" id="department" value="" required />
	</div>
	<div data-role="fieldcontain">
    <label for="email">Courriel :</label>
    <input type="email" name="email" id="email" value="" required />
	</div>
	<div data-role="fieldcontain">
	    <label for="phone_office">Tel. bureau :</label>
	    <input type="tel" name="phone_office" id="phone_office" value=""  />
	</div>
	<div data-role="fieldcontain">
	    <label for="phone_mobile">Tel. mobile :</label>
	    <input type="tel" name="phone_mobile" id="phone_mobile" value=""  />
	</div>
	<div data-role="fieldcontain">
	    <label for="phone_fax">Tel. fax :</label>
	    <input type="tel" name="phone_fax" id="phone_fax" value=""  />
	</div>
	<div data-role="fieldcontain">
	    <label for="street">Rue :</label>
	    <input type="text" name="street" id="street" value=""  />
	</div>
	<div data-role="fieldcontain">
	    <label for="city">Ville :</label>
	    <input type="text" name="city" id="city" value=""  />
	</div>
	<div data-role="fieldcontain">
	    <label for="state">Etat :</label>
	    <input type="text" name="state" id="state" value=""  />
	</div>
	<div data-role="fieldcontain">
	    <label for="post_code">Code postal :</label>
	    <input type="text" name="post_code" id="post_code" value=""  />
	</div>
	<div data-role="fieldcontain">
	    <label for="country">Pays :</label>
	    <input type="text" name="country" id="country" value=""  />
	</div>
</form>

