<?php
/** 
 * Copyright (c) 2011, Cédric DERUE
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the University of California, Berkeley nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
 
  // Stocke le titre de l'entête dans une variable de layout
  $this->broker('layout')->getLayout()->assign('header', $this->lead->getFullname());
  // Stocke la configuration des boutons du menu de pied de page
  $options = array();
  $options[] = array(
    'action' => 'Retour',
    'icon'   => 'back',
    'url'    => '/lead/list'
  );
  $options[] = array(
    'action' => 'Editer',
    'icon'   => 'gear',
    'url'    => '/lead/edit/id/' . $this->lead->getId()
  );
  $this->broker('layout')->getLayout()->assign('footer', $options);
?>

<div class="ui-body ui-body-c">
  <dl class="details">
  <?php if ($this->lead->getSociety()): ?>
  <dt>Société :</dt>
  <dd><?php echo $this->lead->getSociety(); ?></dd>
  <?php endif; ?>
  
  <?php if ($this->lead->getDepartment()): ?>
  <dt>Département :</dt>
  <dd><?php echo $this->lead->getDepartment(); ?></dd>
  <?php endif; ?>
  
  <?php if ($this->lead->getJobTitle()): ?>
  <dt>Fonction :</dt> 
  <dd><?php echo $this->lead->getJobTitle(); ?></dd>
  <?php endif; ?>
  
  <?php if ($this->lead->getEmail()): ?>
  <dt>Courriel :</dt>
  <dd><a href="mailto:<?php echo $this->lead->getEmail(); ?>"><?php echo $this->lead->getEmail(); ?></a></dd>
  <?php endif; ?>
  
  <?php if ($this->lead->getPhoneOffice()): ?>
  <dt>Tél. Bureau :</dt>
  <dd><a href="tel:<?php echo $this->lead->getPhoneOffice(); ?>"><?php echo $this->lead->getPhoneOffice(); ?></a></dd>
  <?php endif; ?>
  
  <?php if ($this->lead->getPhoneMobile()): ?>
  <dt>Tél. Mobile :</dt>
  <dd><a href="tel:<?php echo $this->lead->getPhoneOffice(); ?>"><?php echo $this->lead->getPhoneOffice(); ?></a></dd>
  <?php endif; ?>
  
  <?php if ($this->lead->getPhoneFax()): ?>
  <dt>Tél. Fax :</dt>
  <dd><?php echo $this->lead->getPhoneFax(); ?></dd>
  <?php endif; ?>
  </dl>
  
  <?php if (null === $this->lead->getAddress()): ?>
  
  <?php endif; ?>
</div>